spring:
  application:
    name: ${APP_NAME:union-bbs}
  datasource:
    url: jdbc:mysql://localhost:3306/unionbbs
    username: root
    password: Liuwenxing1!
    dirver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1